pretranslate:
  segments:
    ignore_patterns:
    - "{# wf_(?!featured_snippet).*#}"
    - "^(Note|Caution|Warning|Success|Key Point|Key Term|Objective|Dogfood): "
    - "{:.*}"
    - "{%.*%}"
    ignore_frontmatter_keys:
    - "layout"
    - "permalink"
  paths:
  - source: .
    include:
    - "index.md"
