pretranslate:
  segments:
    ignore_patterns:
    - !ruby/regexp /{%\s?([a-zA-Z0-9\.\-\?\'\"\s]*)\s?%}/
    ignore_frontmatter_keys:
    - "layout"
    - "permalink"
  paths:
  - source: .
    include:
    - "index.md"
